FROM node:lts-bullseye AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --build-from-source

COPY . .
RUN npm run build

FROM node:lts-bullseye AS runner
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

RUN npm rebuild better-sqlite3 --build-from-source

COPY --from=builder /app/package*.json ./
EXPOSE 3000
CMD ["node", "dist/main"]

