services:
  client:
    container_name: sapphire-app-client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sapphire-app-client
    ports:
      - "8080:8080"
    restart: unless-stopped
  server:
    container_name: sapphire-app-server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    command: ["npm", "run", "start:prod"]