version: "3.8"
services:
  client:
    container_name: sapphire-app-client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: sapphire-app-client
    ports:
      - "3000:80"
    restart: unless-stopped
