services:
  server:
    build:
      context: ./src-server
      dockerfile: dockerfile
    networks:
      - app-net

  client:
    build:
      context: ./src-client
      dockerfile: dockerfile
    ports:
      - '80:4173'
    environment:
      - VITE_API_URL=http://backend:3000
    depends_on:
      - server
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
