/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsCreateRouteImport } from './routes/projects/create'
import { Route as ProjectsUuidRouteRouteImport } from './routes/projects/$uuid/route'
import { Route as ProjectsUuidIndexRouteImport } from './routes/projects/$uuid/index'
import { Route as ProjectsUuidEditRouteImport } from './routes/projects/$uuid/edit'

const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsUuidRouteRoute = ProjectsUuidRouteRouteImport.update({
  id: '/$uuid',
  path: '/$uuid',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsUuidIndexRoute = ProjectsUuidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsUuidRouteRoute,
} as any)
const ProjectsUuidEditRoute = ProjectsUuidEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProjectsUuidRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/projects/$uuid': typeof ProjectsUuidRouteRouteWithChildren
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$uuid/edit': typeof ProjectsUuidEditRoute
  '/projects/$uuid/': typeof ProjectsUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/create': typeof ProjectsCreateRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$uuid/edit': typeof ProjectsUuidEditRoute
  '/projects/$uuid': typeof ProjectsUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/projects/$uuid': typeof ProjectsUuidRouteRouteWithChildren
  '/projects/create': typeof ProjectsCreateRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$uuid/edit': typeof ProjectsUuidEditRoute
  '/projects/$uuid/': typeof ProjectsUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$uuid'
    | '/projects/create'
    | '/projects/'
    | '/projects/$uuid/edit'
    | '/projects/$uuid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/create'
    | '/projects'
    | '/projects/$uuid/edit'
    | '/projects/$uuid'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$uuid'
    | '/projects/create'
    | '/projects/'
    | '/projects/$uuid/edit'
    | '/projects/$uuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/create': {
      id: '/projects/create'
      path: '/create'
      fullPath: '/projects/create'
      preLoaderRoute: typeof ProjectsCreateRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/$uuid': {
      id: '/projects/$uuid'
      path: '/$uuid'
      fullPath: '/projects/$uuid'
      preLoaderRoute: typeof ProjectsUuidRouteRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/$uuid/': {
      id: '/projects/$uuid/'
      path: '/'
      fullPath: '/projects/$uuid/'
      preLoaderRoute: typeof ProjectsUuidIndexRouteImport
      parentRoute: typeof ProjectsUuidRouteRoute
    }
    '/projects/$uuid/edit': {
      id: '/projects/$uuid/edit'
      path: '/edit'
      fullPath: '/projects/$uuid/edit'
      preLoaderRoute: typeof ProjectsUuidEditRouteImport
      parentRoute: typeof ProjectsUuidRouteRoute
    }
  }
}

interface ProjectsUuidRouteRouteChildren {
  ProjectsUuidEditRoute: typeof ProjectsUuidEditRoute
  ProjectsUuidIndexRoute: typeof ProjectsUuidIndexRoute
}

const ProjectsUuidRouteRouteChildren: ProjectsUuidRouteRouteChildren = {
  ProjectsUuidEditRoute: ProjectsUuidEditRoute,
  ProjectsUuidIndexRoute: ProjectsUuidIndexRoute,
}

const ProjectsUuidRouteRouteWithChildren =
  ProjectsUuidRouteRoute._addFileChildren(ProjectsUuidRouteRouteChildren)

interface ProjectsRouteRouteChildren {
  ProjectsUuidRouteRoute: typeof ProjectsUuidRouteRouteWithChildren
  ProjectsCreateRoute: typeof ProjectsCreateRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsUuidRouteRoute: ProjectsUuidRouteRouteWithChildren,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
